version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8082:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8083
    depends_on:
      - backend
    volumes:
      - ./src:/app/src
      - ./public:/app/public

  backend:
    build: ./backend
    ports:
      - "8083:8080"
    environment:
      - GOOGLE_CLOUD_PROJECT=agentic-466414
      - GOOGLE_CLOUD_LOCATION=europe-west4
      - GOOGLE_GENAI_USE_VERTEXAI=FALSE
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

networks:
  default:
    name: finzen-network 